project_id = "szjkvanaqarmeetqtxue"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:5173"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://lovable.dev"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# Allow/disallow new user signups via email to your project.
enable_signup = true
# Allow/disallow testing manual linking of accounts
enable_manual_linking = false

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false
# If enabled, users will need to reauthenticate or have logged in recently to change their password.
secure_password_change = false

# Use a production-ready SMTP server
[auth.email.smtp]
host = "smtp.resend.com"
port = 587
user = "resend"
# Update max_frequency to a lower frequency if you expect a high volume of auth emails
max_frequency = "1s"
admin_email = "admin@example.com"
sender_name = "Spendenlauf Lüneburg"

[functions.send-confirmation-email]
verify_jwt = false